name: shutter-explorer
services:
  backend:
    build: 
      context: ../backend/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVER_PORT: 5000
      OBSERVER_DB_HOST: ${OBSERVER_DB_INSTANCE}
      OBSERVER_DB_PORT: ${OBSERVER_DB_PORT}
      OBSERVER_DB_USER: postgres
      OBSERVER_DB_PASSWORD: ${OBSERVER_DB_PASSWORD}
      OBSERVER_DB_NAME: postgres
      OBSERVER_DB_SSL_MODE: disable
      ERPC_DB_HOST: 
      ERPC_DB_PORT: 
      ERPC_DB_USER: 
      ERPC_DB_PASSWORD: 
      ERPC_DB_NAME: 
      ERPC_DB_SSL_MODE: 
      GENESIS_TIMESTAMP: 
      SLOT_DURATION: 
      SLOTS_PER_EPOCH: 
      TOTAL_GNOSIS_VALIDATORS: 
    command: ["./backend"]
    labels:
      caddy: "${SERVICE_DOMAIN_NAME}"
      caddy.@browser: "method GET"
      caddy.reverse_proxy: "{{ upstreams 5000 }}"
      caddy.header.Access-Control-Allow-Origin: "*"
      caddy.header.Access-Control-Allow-Methods: "GET, POST, OPTIONS"
      caddy.header.Access-Control-Allow-Headers: "Content-Type, Authorization"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    restart: always
    volumes:
      - ${DATA_DIR:-./data}/caddy:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - "443:443"
      - "443:443/udp"
    labels:
      caddy.email: "devops@brainbot.com"