name: Build and Deploy

on:
  push:
    branches:
        - main
        - staging

jobs:
    deploy_instance_1:
        if: github.ref == 'refs/heads/staging'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to Instance 1
              uses: appleboy/ssh-action@v0.1.8
              with:
                host: ${{ secrets.INSTANCE_1_SERVER_HOST }}
                username: ${{ secrets.INSTANCE_1_SERVER_USER }}
                key: ${{ secrets.SERVER_KEY }}
                script: |
                    cd /root/shutter-explorer
                    git pull origin staging
                    cd docker
                    docker compose up -d --build

    deploy_instance_2:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to Instance 2
              uses: appleboy/ssh-action@v0.1.8
              with:
                host: ${{ secrets.INSTANCE_2_SERVER_HOST }}
                username: ${{ secrets.INSTANCE_2_SERVER_USER }}
                key: ${{ secrets.SERVER_KEY }}
                script: |
                    cd /root/shutter-explorer
                    git pull origin main
                    cd docker
                    docker compose up -d --build